#!/usr/bin/env ruby

require 'open3'
require 'pry'
require 'json'

aws_cli_installed = system('which aws', out: File::NULL)

unless aws_cli_installed
  puts 'Missing dependency: AWS CLI is not installed.'
  puts 'Visit https://aws.amazon.com/cli/ and install the AWS CLI, then try the exo command again.'
  exit
end

if ARGV[0] == 'launch'
  system('shell/launch.sh')
  exit
end

if ARGV[0] == 'describe-instances'
  system('aws ec2 describe-instances')
  exit
end

if ARGV[0] == 'dns'
  response, _, _ = Open3.capture3('aws ec2 describe-instances')

  JSON.parse(response)['Reservations'].each do |data|
    puts data['Instances'][0]['PublicDnsName']
  end

  exit
end

puts 'usage: exo [command]'
puts
puts 'These are the commands you can use:'
puts 'launch                 Launch a new EC2 instance'
puts 'describe-instances     Alias for aws ec2 describe-instances'
puts 'dns                    List public DNS names for all EC2 instances'
