#!/usr/bin/env ruby

aws_cli_installed = system('which aws', out: File::NULL)

unless aws_cli_installed
  puts 'Missing dependency: AWS CLI is not installed.'
  puts 'Visit https://aws.amazon.com/cli/ and install the AWS CLI, then try the exo command again.'
  exit
end

if ARGV[0] == 'launch'
  system('shell/launch.sh')
  exit
end

if ARGV[0] == 'describe-instances'
  system('aws ec2 describe-instances')
  exit
end

puts 'usage: exo [command]'
puts
puts 'These are the commands you can use:'
puts 'launch                 Launch a new EC2 instance'
puts 'describe-instances     Alias for aws ec2 describe-instances'
